import http.server
import socketserver
import socket

rawtext = ''

class MyHttpRequestHandler(http.server.SimpleHTTPRequestHandler):

    def do_GET(self):
        global rawtext
        # Sending an '200 OK' response
        self.send_response(200)

        # Setting the header
        self.send_header("Content-type", "text/html")

        # Whenever using 'send_header', you also have to call 'end_headers'
        self.end_headers()

        # Some custom HTML code, possibly generated by another function
        #  html = f"<html><head></head><body><h1>Hello {self.text}!</h1></body></html>"
        html = rawtext

        # Writing the HTML contents with UTF-8
        self.wfile.write(bytes(html, "utf8"))

        return

def serveRawText(text:str):
    global rawtext
    rawtext = text

    # Create an object of the above class
    handler_object = MyHttpRequestHandler

    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("8.8.8.8", 80))
    ip = s.getsockname()[0]

    PORT = 8000
    my_server = socketserver.TCPServer(("", PORT), handler_object)
    print(f"serving playlist at: {ip}:{PORT}")

    # Star the server
    try:
        my_server.serve_forever()
    except KeyboardInterrupt:
        exit()

if __name__ == "__main__":
    import sys
    arg = sys.argv[-1]

    with open(arg) as text:
        serveRawText(text.read())
