name: README Update Scraper Status

on:
  push:
    paths:
      - '**.toml'
  schedule:
    - cron: '0 0 1 * *'

jobs:
  update_templates:
    name: "Update Templates"
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Update GitHub Readme"
        uses: actions/checkout@main

      # Runs a set of commands using the runners shell
      - name: Update README.md with Scraper Status
        run: |
          pip install -r requirements.txt
          python scraper_status.py

      - name: commit
        run: |
          git config --global user.email alanjoses.29@gmail.com
          git config --global user.name AlanJs26
          git add .
          git commit -m "README Scraper Status" -a

      - name: Push changes
        # uses: ad-m/github-push-action@master
        uses: CasperWA/push-protected@v2
        # with:
        #   github_token: ${{ secrets.GITHUB_TOKEN }}

        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          branch: main
